services:
  dwh_pipeline:
    platform: linux/amd64 # mac m chip specific
    build:
      context: .
      dockerfile: dockerfile.dwh
    ports:
      - "3000:3000"
    image: crhranalyticse11-e6dffre2d2daghdb.azurecr.io/hr-pipeline:latest

  dashboard:
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfile.dashboard
    ports:
      - "8501:8501"
    image: crhranalyticse11-e6dffre2d2daghdb.azurecr.io/dashboard:latest

