services:
  dwh_pipeline:
    platform: linux/amd64 # mac m chip specific
    build:
      context: .
      dockerfile: dockerfile.dwh
    ports:
      - "3000:3000"
    image: crhranalytis-e6dffre2d2daghdb.azurecr.io/hr-pipeline:latest

