models:

  - name: fct_job_ads
    description: "Fact table containing job advertisements"
    columns:
      # OCCUPATION_ID
      - name: occupation_id
        description: "Foreign key to dim_occupation"
        tests:
          # Group 1: Uniqueness and Not-Null Tests
          - not_null
          
          # Group 2: Relationship Tests
          - relationships:
              to: ref('dim_occupation')
              field: occupation_id
      
      # EMPLOYER_ID
      - name: employer_id
        description: "Foreign key to dim_employer"
        tests:
          # Group 1: Uniqueness and Not-Null Tests
          # NOTE: 21 records fail this test - these job ads won't be linked to employer data
          - not_null
          
          # Group 2: Relationship Tests
          - relationships:
              to: ref('dim_employer')
              field: employer_id
      
      # LOCATION_ID
      - name: location_id
        description: "Foreign key to dim_location"
        tests:
          # Group 1: Uniqueness and Not-Null Tests
          # NOTE: 56 records fail this test - these job ads won't have location data
          - not_null
          
          # Group 2: Relationship Tests
          - relationships:
              to: ref('dim_location')
              field: location_id
                
  # DIMENSION TABLES TESTS
  # Tests for dimension tables focus on primary key integrity and hierarchical relationships
  
  - name: dim_occupation
    description: "Dimension table for job occupation categories"
    columns:
      - name: occupation_id
        description: "Surrogate key for occupation"
        tests:
          # Uniqueness and Not-Null Tests
          - unique
          - not_null
      - name: occupation_label
        description: "Specific job title or role"
        tests:
          # Uniqueness and Not-Null Tests
          - not_null
      - name: occupation_group
        description: "Group that the occupation belongs to"
        tests:
          # Uniqueness and Not-Null Tests
          - not_null
      - name: occupation_field
        description: "Broader field that the occupation belongs to"
        tests:
          # Uniqueness and Not-Null Tests
          - not_null
  
  - name: dim_employer
    description: "Dimension table for employer information"
    columns:
      - name: employer_id
        description: "Surrogate key for employer"
        tests:
          # Uniqueness and Not-Null Tests
          - unique
          - not_null
      - name: employer_organization_number
        description: "Organization identification number"
        tests:
          # Uniqueness and Not-Null Tests
          # KNOWN ISSUE: 19 employers are missing organization numbers.
          # See docs/data_quality_issues.md for details.
          - not_null
      - name: employer_name
        description: "Name of the employer"
        tests:
          # Uniqueness and Not-Null Tests
          - not_null
  
  - name: dim_location
    description: "Dimension table for geographic locations"
    columns:
      - name: location_id
        description: "Surrogate key for location"
        tests:
          # Uniqueness and Not-Null Tests
          - unique
          - not_null
      - name: location_country_code
        description: "Country code"
        tests:
          # Uniqueness and Not-Null Tests
          - not_null
      - name: location_region_code
        description: "Region code within country"
      - name: location_municipality_code
        description: "Municipality code within region"
  
  - name: dim_job_details
    description: "Dimension table for job details"
    columns:
      - name: job_details_id
        description: "Surrogate key for job details"
        tests:
          # Uniqueness and Not-Null Tests
          # KNOWN ISSUE: 5 job_details_id values are duplicated.
          # See docs/data_quality_issues.md for details.
          - unique
          - not_null
      - name: job_ad_id
        description: "Original job ad identifier"
        tests:
          # Uniqueness and Not-Null Tests
          - not_null
  
  - name: dim_auxilliary_attributes
    description: "Dimension table for additional job attributes"
    columns:
      - name: auxilliary_attributes_id
        description: "Surrogate key for auxiliary attributes"
        tests:
          # Uniqueness and Not-Null Tests
          - unique
          - not_null

  # FACT TABLE TESTS
  # Tests for fact tables focus on foreign key relationships, data types, and value ranges
  
  - name: fct_job_ads
    description: "Fact table containing job advertisements"
    columns:
      - name: occupation_id
        description: "Foreign key to dim_occupation"
        tests:
          # Uniqueness and Not-Null Tests
          - not_null
          
          # Relationship Tests
          - relationships:
              to: ref('dim_occupation')
              field: occupation_id
      
      - name: employer_id
        description: "Foreign key to dim_employer"
        tests:
          # Uniqueness and Not-Null Tests
          # KNOWN ISSUE: 21 job ads are missing employer information.
          # See docs/data_quality_issues.md for details.
          - not_null
          
          # Relationship Tests
          - relationships:
              to: ref('dim_employer')
              field: employer_id
      
      - name: location_id
        description: "Foreign key to dim_location"
        tests:
          # Uniqueness and Not-Null Tests
          # KNOWN ISSUE: 56 job ads are missing location information.
          # See docs/data_quality_issues.md for details.
          - not_null
          
          # Relationship Tests
          - relationships:
              to: ref('dim_location')
              field: location_id
      
      # JOB_DETAILS_ID
      - name: job_details_id
        description: "Foreign key to dim_job_details"
        tests:
          # Uniqueness and Not-Null Tests
          - not_null
          
          # Relationship Tests
          # KNOWN ISSUE: Related to the 5 duplicate job_details_id values in dim_job_details.
          # See docs/data_quality_issues.md for details.
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id
      
      # AUXILLIARY_ATTRIBUTES_ID
      - name: auxilliary_attributes_id
        description: "Foreign key to dim_auxilliary_attributes"
        tests:
          # Group 1: Uniqueness and Not-Null Tests
          - not_null
          
          # Group 2: Relationship Tests
          - relationships:
              to: ref('dim_auxilliary_attributes')
              field: auxilliary_attributes_id
      
      # RELEVANCE
      - name: relevance
        description: "Relevance score of the job ad"
        tests:
          # Group 1: Uniqueness and Not-Null Tests
          - not_null
          
          # Group 3: Column Value Expectation Tests
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0  
              max_value: 1 
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      
      # VACANCIES
      - name: vacancies
        description: "Number of open positions in the job ad"
        tests: 
          # Uniqueness and Not-Null Tests
          # KNOWN ISSUE: 1 job ad is missing vacancy count information.
          # See docs/data_quality_issues.md for details.
          - not_null
          
          # Column Value Expectation Tests
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 1
              max_value: 20
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 20
              config:
                severity: warn
                # KNOWN ISSUE: At least one job ad has vacancies > 20.
                # See docs/data_quality_issues.md for details.
      
      - name: publication_date
        description: "Date when the job ad was published"
        tests:
          # Group 1: Uniqueness and Not-Null Tests
          - not_null
          
          # Group 4: Custom SQL Tests for Data Consistency
          # Example: Could add custom tests for valid date ranges
      
      - name: application_deadline
        description: "Deadline for job applications"
        tests:
          # Group 1: Uniqueness and Not-Null Tests
          - not_null
          
          # Group 4: Custom SQL Tests for Data Consistency
          # Example: Could add custom tests for deadline > publication_date
          
          # Custom SQL Tests could be added here for deadline validations