sources:
  - name: job_ads
    schema: staging
    tables:
      - name: stg_ads
        identifier: technical_field_job_ads
      - name: stg_coords
        identifier: technical_field_job_ads__workplace_address__coordinates
